# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'permissions': (('approve_items', 'Approve items'),)},
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.TextField(choices=[('approved', 'approved'), ('pending', 'pending'), ('rejected', 'rejected')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.TextField(choices=[('project', 'project'), ('preprint', 'preprint'), ('registration', 'registration'), ('file', 'file'), ('website', 'website')]),
        ),
    ]
